"""empty message

Revision ID: 506264c08dd5
Revises: e0bcf16d53b7
Create Date: 2020-01-07 07:14:54.938349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506264c08dd5'
down_revision = 'e0bcf16d53b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'motor', ['serial'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'motor', type_='unique')
    # ### end Alembic commands ###
