"""empty message

Revision ID: 9cd6dcec643e
Revises: db14ee33f146
Create Date: 2020-01-07 03:25:01.758296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd6dcec643e'
down_revision = 'db14ee33f146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'date')
    # ### end Alembic commands ###
