"""empty message

Revision ID: b1e3e6109815
Revises: 1e4001b4ccb9
Create Date: 2020-01-09 12:32:24.649093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e3e6109815'
down_revision = '1e4001b4ccb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('status', sa.String(length=6), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'status')
    # ### end Alembic commands ###
