"""empty message

Revision ID: c6c931846049
Revises: b1e3e6109815
Create Date: 2020-01-14 02:15:04.231568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6c931846049'
down_revision = 'b1e3e6109815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'corriente')
    op.drop_column('test', 'voltaje')
    op.drop_column('test', 'ruido')
    op.drop_column('test', 'vibracion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('vibracion', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('test', sa.Column('ruido', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('test', sa.Column('voltaje', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('test', sa.Column('corriente', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
