"""empty message

Revision ID: db14ee33f146
Revises: 395dc8374127
Create Date: 2020-01-07 03:21:48.000165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db14ee33f146'
down_revision = '395dc8374127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('date', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
