"""empty message

Revision ID: e19e17c67f4a
Revises: c6c931846049
Create Date: 2020-01-14 02:16:38.381190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19e17c67f4a'
down_revision = 'c6c931846049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('corriente', sa.String(length=60), nullable=False))
    op.add_column('test', sa.Column('ruido', sa.String(length=60), nullable=False))
    op.add_column('test', sa.Column('vibracion', sa.String(length=60), nullable=False))
    op.add_column('test', sa.Column('voltaje', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'voltaje')
    op.drop_column('test', 'vibracion')
    op.drop_column('test', 'ruido')
    op.drop_column('test', 'corriente')
    # ### end Alembic commands ###
