"""empty message

Revision ID: e610e6dd234a
Revises: e19e17c67f4a
Create Date: 2020-01-28 16:25:42.763881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e610e6dd234a'
down_revision = 'e19e17c67f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('statusCorriente', sa.String(length=6), nullable=False))
    op.add_column('test', sa.Column('statusRuido', sa.String(length=6), nullable=False))
    op.add_column('test', sa.Column('statusVibracion', sa.String(length=6), nullable=False))
    op.add_column('test', sa.Column('statusVoltaje', sa.String(length=6), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'statusVoltaje')
    op.drop_column('test', 'statusVibracion')
    op.drop_column('test', 'statusRuido')
    op.drop_column('test', 'statusCorriente')
    # ### end Alembic commands ###
