"""empty message

Revision ID: ed11278da92d
Revises: cde113114b00
Create Date: 2020-01-07 02:21:55.000024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed11278da92d'
down_revision = 'cde113114b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('date', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'date')
    # ### end Alembic commands ###
